### ISSUE TITLE
Feature Request: Wasabi support

### ISSUE THREAD

**Issue by dadealus** [joch/docker-s3backup#2]
I tried adding in the  --endpoint-url=https://s3.wasabisys.com

Is it possible to support other s3 endpoints?

**Comment by dadealus** [comment]
I think I figured it out...

--host=https://s3.wasabisys.com

**Comment by dadealus** [comment]
Ended up needing this in the Docker Args for it to work on wasabi

--host=https://s3.wasabisys.com --host-bucket=**BUCKET-NAMEHERE**.s3.wasabisys.com

Works great. thanks

**Comment by joch** [comment]
Great that you got it working! I'm also a happy Wasabi customer. :)
